import 'dart:async';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_linkify/flutter_linkify.dart';
import 'package:intl/intl.dart';
import 'package:just_audio/just_audio.dart';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:record/record.dart';
import 'package:url_launcher/url_launcher.dart';
import '../api/api_client.dart';
import '../models/support_models.dart';

class ConversationScreen extends StatefulWidget {
  const ConversationScreen({super.key,required this.api,required this.user,required this.initialTicket});
  final ApiClient api; final SupportUser user; final SupportTicket initialTicket;
  @override State<ConversationScreen> createState()=>_ConversationScreenState();
}
class _ConversationScreenState extends State<ConversationScreen>{
  final _composer=TextEditingController(),_scroll=ScrollController(),_recorder=AudioRecorder();
  StreamSubscription<Map<String,dynamic>>? _events; Timer? _debounce,_recordTimer; late SupportTicket _ticket; bool _sending=false,_recording=false,_internal=false; Duration _duration=Duration.zero; String? _error;
  @override void initState(){super.initState();_ticket=widget.initialTicket;_events=widget.api.supportEvents().listen((e){if(e['ticketId']?.toString()!=_ticket.id)return;_debounce?.cancel();_debounce=Timer(const Duration(milliseconds:180),_refresh);});WidgetsBinding.instance.addPostFrameCallback((_)=>_bottom());}
  @override void dispose(){_composer.dispose();_scroll.dispose();_events?.cancel();_debounce?.cancel();_recordTimer?.cancel();_recorder.dispose();super.dispose();}
  Future<void> _refresh() async {try{final items=await widget.api.loadTickets();final found=items.where((x)=>x.id==_ticket.id);if(found.isNotEmpty&&mounted){setState(()=>_ticket=found.first);WidgetsBinding.instance.addPostFrameCallback((_)=>_bottom(animated:true));}}catch(_){}}
  Future<void> _send() async {final text=_composer.text.trim();if(text.isEmpty||_sending)return;setState((){_sending=true;_error=null;});try{final t=await widget.api.sendMessage(_ticket.id,text,isInternal:_internal);if(mounted)setState((){_ticket=t;_composer.clear();});WidgetsBinding.instance.addPostFrameCallback((_)=>_bottom(animated:true));}on ApiException catch(e){if(mounted)setState(()=>_error=e.message);}finally{if(mounted)setState(()=>_sending=false);}}
  Future<void> _pick() async {final r=await FilePicker.platform.pickFiles(allowMultiple:false);final p=r?.files.single.path;if(p!=null)await _upload(p);}
  Future<void> _upload(String path,{String? body,String? mime}) async {setState(()=>_sending=true);try{final t=await widget.api.uploadAttachment(_ticket.id,path,body:body,isInternal:_internal,mimeType:mime);if(mounted)setState(()=>_ticket=t);}on ApiException catch(e){if(mounted)setState(()=>_error=e.message);}finally{if(mounted)setState(()=>_sending=false);}}
  Future<void> _record() async {if(_recording){await _finishRecord();return;}if(!await _recorder.hasPermission()){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Microphone permission is required.')));return;}final temp=await getTemporaryDirectory();final path='${temp.path}${Platform.pathSeparator}arofi_voice_${DateTime.now().millisecondsSinceEpoch}.m4a';await _recorder.start(const RecordConfig(encoder:AudioEncoder.aacLc,bitRate:96000,sampleRate:44100),path:path);_recordTimer?.cancel();setState((){_recording=true;_duration=Duration.zero;});_recordTimer=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>_duration+=const Duration(seconds:1));});}
  Future<void> _finishRecord() async {_recordTimer?.cancel();final p=await _recorder.stop();if(mounted)setState(()=>_recording=false);if(p!=null)await _upload(p,body:'Voice message',mime:'audio/mp4');}
  Future<void> _cancelRecord() async {_recordTimer?.cancel();await _recorder.cancel();if(mounted)setState((){_recording=false;_duration=Duration.zero;});}
  Future<void> _claim()=>_assign(widget.user.id);
  Future<void> _assign(String? id) async {setState(()=>_sending=true);try{final t=await widget.api.updateTicket(_ticket.id,assigneeUserId:id,includeAssignee:true);if(mounted)setState(()=>_ticket=t);}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>_sending=false);}}
  Future<void> _transfer() async {final staff=await widget.api.loadStaff();if(!mounted)return;final selected=await showModalBottomSheet<SupportAgent?>(context:context,showDragHandle:true,builder:(ctx)=>SafeArea(child:ListView(shrinkWrap:true,children:[const ListTile(title:Text('Transfer conversation',style:TextStyle(fontWeight:FontWeight.w800))),ListTile(leading:const Icon(Icons.person_off_outlined),title:const Text('Unassign to shared inbox'),onTap:()=>Navigator.pop(ctx,const SupportAgent(id:'',email:'',displayName:'',role:''))),...staff.map((a)=>ListTile(leading:CircleAvatar(child:Text(_initials(a.displayName))),title:Text(a.displayName),subtitle:Text('${a.role} · ${a.email}'),onTap:()=>Navigator.pop(ctx,a)))])));if(selected!=null)await _assign(selected.id.isEmpty?null:selected.id);}
  Future<void> _status(String s) async {setState(()=>_sending=true);try{final t=await widget.api.updateTicket(_ticket.id,status:s);if(mounted)setState(()=>_ticket=t);}finally{if(mounted)setState(()=>_sending=false);}}
  void _bottom({bool animated=false}){if(!_scroll.hasClients)return;final p=_scroll.position.maxScrollExtent;if(animated){_scroll.animateTo(p,duration:const Duration(milliseconds:220),curve:Curves.easeOut);}else{_scroll.jumpTo(p);}}
  String _initials(String s)=>s.trim().split(RegExp(r'\s+')).where((x)=>x.isNotEmpty).take(2).map((x)=>x[0].toUpperCase()).join();
  String _pretty(String s)=>s.toLowerCase().replaceAll('_',' ').split(' ').map((e)=>e.isEmpty?'':'${e[0].toUpperCase()}${e.substring(1)}').join(' ');
  @override Widget build(BuildContext context){final c=Theme.of(context).colorScheme,unassigned=_ticket.assignedTo==null||_ticket.assignedTo!.isEmpty;return Scaffold(appBar:AppBar(titleSpacing:0,title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_ticket.openedBy?.isNotEmpty==true?_ticket.openedBy!: _ticket.subject,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800)),Text('${_ticket.reference} · ${_ticket.isLiveChat?'Live chat':_ticket.channel}',style:TextStyle(fontSize:10.5,color:c.onSurfaceVariant))]),actions:[if(unassigned&&widget.user.canWriteSupport)TextButton.icon(onPressed:_sending?null:_claim,icon:const Icon(Icons.person_add_alt_1,size:17),label:const Text('Claim')),PopupMenuButton<String>(onSelected:(v){if(v=='transfer')_transfer();else if(v.startsWith('status:'))_status(v.substring(7));},itemBuilder:(_)=>[if(widget.user.canWriteSupport)const PopupMenuItem(value:'transfer',child:ListTile(leading:Icon(Icons.swap_horiz),title:Text('Transfer'))),const PopupMenuDivider(),...['OPEN','IN_PROGRESS','PENDING_CUSTOMER','RESOLVED','CLOSED'].map((s)=>PopupMenuItem(value:'status:$s',child:ListTile(leading:Icon(s==_ticket.status?Icons.radio_button_checked:Icons.radio_button_off),title:Text(_pretty(s)))))] )]),body:Column(children:[_Info(ticket:_ticket),if(_error!=null)Container(width:double.infinity,color:c.errorContainer,padding:const EdgeInsets.all(8),child:Text(_error!,style:TextStyle(color:c.onErrorContainer))),Expanded(child:RefreshIndicator(onRefresh:_refresh,child:ListView.builder(controller:_scroll,physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(12),itemCount:_ticket.messages.length,itemBuilder:(_,i)=>_Bubble(message:_ticket.messages[i],api:widget.api)))),if(_recording)_RecordBar(duration:_duration,onCancel:_cancelRecord,onSend:_finishRecord)else _Composer(controller:_composer,internal:_internal,busy:_sending,canWrite:widget.user.canWriteSupport,onInternal:(v)=>setState(()=>_internal=v),onAttach:_pick,onMic:_record,onSend:_send)]));}
}
class _Info extends StatelessWidget{const _Info({required this.ticket});final SupportTicket ticket;@override Widget build(BuildContext context){final c=Theme.of(context).colorScheme;final d=[if(ticket.tenantName?.isNotEmpty==true)ticket.tenantName!,if(ticket.email?.isNotEmpty==true)ticket.email!,if(ticket.phoneNumber?.isNotEmpty==true)ticket.phoneNumber!];return Container(width:double.infinity,padding:const EdgeInsets.fromLTRB(14,9,14,9),decoration:BoxDecoration(color:c.surface,border:Border(bottom:BorderSide(color:c.outlineVariant))),child:Row(children:[Text(ticket.status.replaceAll('_',' '),style:TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:c.primary)),const SizedBox(width:10),Expanded(child:Text(d.isEmpty?ticket.subject:d.join(' · '),maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(fontSize:11,color:c.onSurfaceVariant))),if(ticket.assignee!=null)Chip(label:Text(ticket.assignee!.displayName,style:const TextStyle(fontSize:10)),visualDensity:VisualDensity.compact)]));}}
class _Bubble extends StatelessWidget{const _Bubble({required this.message,required this.api});final SupportMessage message;final ApiClient api;@override Widget build(BuildContext context){if(message.isInternal)return Center(child:Container(margin:const EdgeInsets.symmetric(vertical:6),padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:const Color(0xFFFFF7E6),borderRadius:BorderRadius.circular(10)),child:Text('Internal · ${message.authorName}: ${message.body}',style:const TextStyle(color:Color(0xFF8A4F0A),fontSize:11.5))));final customer=message.fromCustomer,c=Theme.of(context).colorScheme,bg=customer?c.surfaceContainerHighest:const Color(0xFF22A53A),fg=customer?c.onSurface:Colors.white;return Align(alignment:customer?Alignment.centerLeft:Alignment.centerRight,child:ConstrainedBox(constraints:BoxConstraints(maxWidth:MediaQuery.sizeOf(context).width*.82),child:Container(margin:const EdgeInsets.symmetric(vertical:4),padding:const EdgeInsets.fromLTRB(12,9,12,8),decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(message.authorName,style:TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:customer?c.primary:Colors.white70)),if(message.body.isNotEmpty)...[const SizedBox(height:3),Linkify(text:message.body,style:TextStyle(color:fg,fontSize:14,height:1.4),linkStyle:TextStyle(color:customer?const Color(0xFF2563EB):Colors.white,decoration:TextDecoration.underline),onOpen:(l)async{final u=Uri.tryParse(l.url);if(u!=null)await launchUrl(u,mode:LaunchMode.externalApplication);})],if(message.attachments.isNotEmpty)...[const SizedBox(height:7),...message.attachments.map((a)=>_Attachment(a:a,api:api,onGreen:!customer))],const SizedBox(height:5),Align(alignment:Alignment.centerRight,child:Text(DateFormat('HH:mm').format(message.createdAt.toLocal()),style:TextStyle(fontSize:9.5,color:customer?c.outline:Colors.white70)))])))));}}
class _Attachment extends StatefulWidget{const _Attachment({required this.a,required this.api,required this.onGreen});final SupportAttachment a;final ApiClient api;final bool onGreen;@override State<_Attachment> createState()=>_AttachmentState();}
class _AttachmentState extends State<_Attachment>{final _player=AudioPlayer();bool _busy=false,_playing=false;@override void initState(){super.initState();_player.playerStateStream.listen((s){if(mounted)setState(()=>_playing=s.playing);});}@override void dispose(){_player.dispose();super.dispose();}Future<void> _open()async{if(_busy)return;setState(()=>_busy=true);try{if(widget.a.isAudio){if(_playing)await _player.pause();else{final url=widget.api.attachmentUrl(widget.a.id),cookie=await widget.api.cookieHeaderFor(Uri.parse(url));if(_player.audioSource==null)await _player.setUrl(url,headers:cookie.isEmpty?null:{'Cookie':cookie});await _player.play();}}else{await OpenFilex.open(await widget.api.downloadAttachment(widget.a));}}finally{if(mounted)setState(()=>_busy=false);}}@override Widget build(BuildContext context){final fg=widget.onGreen?Colors.white:Theme.of(context).colorScheme.onSurface;return InkWell(onTap:_open,child:Container(margin:const EdgeInsets.only(top:4),padding:const EdgeInsets.all(8),decoration:BoxDecoration(border:Border.all(color:fg.withValues(alpha:.18)),borderRadius:BorderRadius.circular(9)),child:Row(mainAxisSize:MainAxisSize.min,children:[if(_busy)SizedBox.square(dimension:18,child:CircularProgressIndicator(strokeWidth:2,color:fg))else Icon(widget.a.isAudio?(_playing?Icons.pause:Icons.play_arrow):Icons.attach_file,size:18,color:fg),const SizedBox(width:7),Flexible(child:Text(widget.a.fileName,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(color:fg,fontSize:11.5,fontWeight:FontWeight.w700)))])));}}
class _Composer extends StatelessWidget{const _Composer({required this.controller,required this.internal,required this.busy,required this.canWrite,required this.onInternal,required this.onAttach,required this.onMic,required this.onSend});final TextEditingController controller;final bool internal,busy,canWrite;final ValueChanged<bool> onInternal;final VoidCallback onAttach,onMic,onSend;@override Widget build(BuildContext context){final c=Theme.of(context).colorScheme;return SafeArea(top:false,child:Container(padding:const EdgeInsets.fromLTRB(10,7,10,9),decoration:BoxDecoration(color:c.surface,border:Border(top:BorderSide(color:c.outlineVariant))),child:Column(mainAxisSize:MainAxisSize.min,children:[if(canWrite)Align(alignment:Alignment.centerLeft,child:FilterChip(label:const Text('Internal note',style:TextStyle(fontSize:10.5)),selected:internal,onSelected:busy?null:onInternal,avatar:const Icon(Icons.lock_outline,size:14))),Row(crossAxisAlignment:CrossAxisAlignment.end,children:[IconButton(onPressed:busy||!canWrite?null:onAttach,icon:const Icon(Icons.attach_file)),IconButton(onPressed:busy||!canWrite?null:onMic,icon:const Icon(Icons.mic_none)),Expanded(child:TextField(controller:controller,enabled:canWrite&&!busy,minLines:1,maxLines:5,decoration:InputDecoration(hintText:internal?'Internal note…':'Message customer…'),onSubmitted:(_)=>onSend())),const SizedBox(width:7),IconButton.filled(onPressed:busy||!canWrite?null:onSend,icon:busy?const SizedBox.square(dimension:17,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.send_rounded))])])));}}
class _RecordBar extends StatelessWidget{const _RecordBar({required this.duration,required this.onCancel,required this.onSend});final Duration duration;final VoidCallback onCancel,onSend;@override Widget build(BuildContext context)=>SafeArea(top:false,child:Container(padding:const EdgeInsets.all(10),color:Theme.of(context).colorScheme.surface,child:Row(children:[const Icon(Icons.fiber_manual_record,color:Colors.red,size:18),const SizedBox(width:8),Expanded(child:Text('Recording ${duration.inMinutes.toString().padLeft(2,'0')}:${(duration.inSeconds%60).toString().padLeft(2,'0')}',style:const TextStyle(fontWeight:FontWeight.w700))),TextButton(onPressed:onCancel,child:const Text('Cancel')),FilledButton.icon(onPressed:onSend,icon:const Icon(Icons.send),label:const Text('Send'))])));}
