class SupportUser {
  const SupportUser({required this.id,required this.email,required this.displayName,required this.role,required this.permissions,this.tenantId,this.tenantName});
  final String id; final String email; final String displayName; final String role; final List<String> permissions; final String? tenantId; final String? tenantName;
  bool get canReadSupport => permissions.contains('ALL') || permissions.contains('support.read');
  bool get canWriteSupport => permissions.contains('ALL') || permissions.contains('support.write');
  factory SupportUser.fromJson(Map<String,dynamic> json)=>SupportUser(id:json['id']?.toString()??'',email:json['email']?.toString()??'',displayName:json['displayName']?.toString()??json['email']?.toString()??'Support',role:json['role']?.toString()??'Support',permissions:(json['permissions'] as List<dynamic>? ?? const []).map((e)=>e.toString()).toList(),tenantId:json['tenantId']?.toString(),tenantName:json['tenantName']?.toString());
}
class SupportAgent { const SupportAgent({required this.id,required this.email,required this.displayName,required this.role}); final String id; final String email; final String displayName; final String role; factory SupportAgent.fromJson(Map<String,dynamic> json)=>SupportAgent(id:json['id']?.toString()??'',email:json['email']?.toString()??'',displayName:json['displayName']?.toString()??json['email']?.toString()??'Support',role:json['role']?.toString()??'Support'); }
class SupportAttachment { const SupportAttachment({required this.id,required this.fileName,required this.mimeType,required this.fileSize,this.createdAt}); final String id; final String fileName; final String mimeType; final int fileSize; final DateTime? createdAt; bool get isAudio=>mimeType.toLowerCase().startsWith('audio/'); bool get isImage=>mimeType.toLowerCase().startsWith('image/'); factory SupportAttachment.fromJson(Map<String,dynamic> json)=>SupportAttachment(id:json['id']?.toString()??'',fileName:json['fileName']?.toString()??'attachment',mimeType:json['mimeType']?.toString()??'application/octet-stream',fileSize:int.tryParse(json['fileSize']?.toString()??'')??0,createdAt:DateTime.tryParse(json['createdAt']?.toString()??'')); }
class SupportMessage { const SupportMessage({required this.id,required this.authorName,required this.authorRole,required this.body,required this.isInternal,required this.createdAt,required this.attachments}); final String id; final String authorName; final String authorRole; final String body; final bool isInternal; final DateTime createdAt; final List<SupportAttachment> attachments; bool get fromCustomer { final r=authorRole.toLowerCase(); return r.contains('customer')||r.contains('business')||r.contains('visitor'); } factory SupportMessage.fromJson(Map<String,dynamic> json)=>SupportMessage(id:json['id']?.toString()??'',authorName:json['authorName']?.toString()??'Unknown',authorRole:json['authorRole']?.toString()??'',body:json['body']?.toString()??'',isInternal:json['isInternal']==true,createdAt:DateTime.tryParse(json['createdAt']?.toString()??'')??DateTime.fromMillisecondsSinceEpoch(0),attachments:(json['attachments'] as List<dynamic>? ?? const []).whereType<Map<String,dynamic>>().map(SupportAttachment.fromJson).toList()); }
class SupportTicket { const SupportTicket({required this.id,required this.reference,required this.subject,required this.category,required this.priority,required this.status,required this.channel,required this.createdAt,required this.messages,this.latestResponseAt,this.openedBy,this.phoneNumber,this.email,this.assignedTo,this.assignee,this.tenantName}); final String id; final String reference; final String subject; final String category; final String priority; final String status; final String channel; final DateTime createdAt; final DateTime? latestResponseAt; final String? openedBy; final String? phoneNumber; final String? email; final String? assignedTo; final SupportAgent? assignee; final String? tenantName; final List<SupportMessage> messages; bool get isLiveChat=>channel.toUpperCase()=='CHAT'||category.toLowerCase()=='live chat'; bool get isOpen=>status=='OPEN'||status=='IN_PROGRESS'||status=='PENDING_CUSTOMER'; SupportMessage? get lastMessage=>messages.isEmpty?null:messages.last; DateTime get sortTime=>latestResponseAt??(messages.isNotEmpty?messages.last.createdAt:createdAt); factory SupportTicket.fromJson(Map<String,dynamic> json){ final a=json['assignee']; final t=json['tenant']; return SupportTicket(id:json['id']?.toString()??'',reference:json['reference']?.toString()??'',subject:json['subject']?.toString()??'Support conversation',category:json['category']?.toString()??'Support',priority:json['priority']?.toString()??'NORMAL',status:json['status']?.toString()??'OPEN',channel:json['channel']?.toString()??'PORTAL',createdAt:DateTime.tryParse(json['createdAt']?.toString()??'')??DateTime.now(),latestResponseAt:DateTime.tryParse(json['latestResponseAt']?.toString()??''),openedBy:json['openedBy']?.toString(),phoneNumber:json['phoneNumber']?.toString(),email:json['email']?.toString(),assignedTo:json['assignedTo']?.toString(),assignee:a is Map<String,dynamic>?SupportAgent.fromJson(a):null,tenantName:t is Map<String,dynamic>?t['name']?.toString():null,messages:(json['messages'] as List<dynamic>? ?? const []).whereType<Map<String,dynamic>>().map(SupportMessage.fromJson).toList()); }}
